//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllCustomerHistory
    {
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public System.DateTime DatePurchased { get; set; }
        public string BookTitle { get; set; }
        public string ShipStreet { get; set; }
        public string ShipCity { get; set; }
        public string ShipST { get; set; }
        public string ShipCountry { get; set; }
        public decimal ShipZip { get; set; }
        public string BillStreet { get; set; }
        public string BillCity { get; set; }
        public string BillST { get; set; }
        public string BillCountry { get; set; }
        public decimal BillZip { get; set; }
        public int BillingAddress { get; set; }
        public decimal CreditCard { get; set; }
        public Nullable<decimal> BookPrice { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
    }
}
