//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        public BOOK()
        {
            this.SHOPPING_CART = new HashSet<SHOPPING_CART>();
        }
    
        public int BookID { get; set; }
        public decimal Isbn { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<decimal> Price { get; set; }
        public decimal Quantity { get; set; }
        public int Publisher_ID { get; set; }
        public int Category_ID { get; set; }
        public decimal CopyDate { get; set; }
        public decimal Cost { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
        public virtual ICollection<SHOPPING_CART> SHOPPING_CART { get; set; }
    }
}
