//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public CATEGORY()
        {
            this.BOOKS = new HashSet<BOOK>();
        }
    
        public int Category_ID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<BOOK> BOOKS { get; set; }
    }
}
