//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCARD
    {
        public CCARD()
        {
            this.CUSTOMER_CCARD = new HashSet<CUSTOMER_CCARD>();
        }
    
        public int CCARDID { get; set; }
        public string CardType { get; set; }
        public decimal CCardNumber { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public decimal ExpirationDate { get; set; }
        public decimal SecurityCode { get; set; }
    
        public virtual ICollection<CUSTOMER_CCARD> CUSTOMER_CCARD { get; set; }
    }
}
