//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_CCARD
    {
        public CUSTOMER_CCARD()
        {
            this.INVOICEs = new HashSet<INVOICE>();
        }
    
        public int CUSTOMER_CCARD_ID { get; set; }
        public int CID { get; set; }
        public int CCardID { get; set; }
    
        public virtual CCARD CCARD { get; set; }
        public virtual CUSTOMER1 CUSTOMER { get; set; }
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
    }
}
