//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER1
    {
        public CUSTOMER1()
        {
            this.CUSTOMER_CCARD = new HashSet<CUSTOMER_CCARD>();
            this.SHOPPING_CART = new HashSet<SHOPPING_CART>();
            this.BILLING_ADDRESS = new HashSet<BILLING_ADDRESS>();
            this.SHIPPING_ADDRESS = new HashSet<SHIPPING_ADDRESS>();
        }
    
        public int CID { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> HPhone { get; set; }
        public Nullable<decimal> WPhone { get; set; }
        public string Email { get; set; }
        public string Pword { get; set; }
        public string LoginStatus { get; set; }
    
        public virtual ICollection<CUSTOMER_CCARD> CUSTOMER_CCARD { get; set; }
        public virtual ICollection<SHOPPING_CART> SHOPPING_CART { get; set; }
        public virtual ICollection<BILLING_ADDRESS> BILLING_ADDRESS { get; set; }
        public virtual ICollection<SHIPPING_ADDRESS> SHIPPING_ADDRESS { get; set; }
    }
}
