//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public int Invoice_ID { get; set; }
        public System.DateTime Date_Of_Purchase { get; set; }
        public int Record_ID { get; set; }
        public int BookID { get; set; }
        public int CUSTOMER_CCARD_ID { get; set; }
    
        public virtual CUSTOMER_CCARD CUSTOMER_CCARD { get; set; }
        public virtual SHOPPING_CART SHOPPING_CART { get; set; }
    }
}
