//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAIL
    {
        public int OrderDetail_ID { get; set; }
        public int Order_ID { get; set; }
        public int BookID { get; set; }
        public int Quantity { get; set; }
        public decimal? UnitPrice { get; set; }
    
        public virtual ORDERR ORDERR { get; set; }
    }
}
