//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_ADDRESS
    {
        public int Pub_Add_ID { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string ST { get; set; }
        public string Country { get; set; }
        public decimal Zip { get; set; }
        public int Publisher_ID { get; set; }
    
        public virtual PUBLISHER PUBLISHER { get; set; }
    }
}
